# Generated by Django 3.0.14 on 2022-06-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheating_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheat_detection', models.ImageField(upload_to='')),
                ('cheat_frames', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='img_upl',
            fields=[
                ('cheating_img_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exam.cheating_img')),
            ],
            bases=('exam.cheating_img',),
        ),
    ]
