# Generated by Django 3.0.14 on 2022-06-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_cheating_img_img_upl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img_upl',
            name='cheating_img_ptr',
        ),
        migrations.DeleteModel(
            name='cheating_img',
        ),
        migrations.DeleteModel(
            name='img_upl',
        ),
    ]
