# Generated by Django 3.0.14 on 2022-06-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220605_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cheat_report',
        ),
    ]
